Upgrade to webpack 5
Without this, `yarn dev` worked but `yarn build` errored with

    ERROR in devtools.js from Terser
    Error: error:0308010C:digital envelope routines::unsupported